-- =======================================================
-- NEXTTEKNO VERİ TABANI KURULUM KODLARI
-- Supabase SQL Editor kısmına yapıştırıp "Run" tuşuna bas.
-- =======================================================

-- 1. Ürünler Tablosu (Products)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  price numeric not null,
  "discountedPrice" numeric,
  reviews numeric default 0,
  imgs jsonb, -- Resimler dosya yolu olarak değil, JSON listesi olarak tutulacak
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Siparişler Tablosu (Orders)
create table if not exists public.orders (
  id text primary key, -- Sipariş No (#1234)
  customer text,
  date text,
  status text,
  total text,
  items jsonb, -- Sipariş içindeki ürünler
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Gerçek Zamanlı Bildirimleri Açma (Realtime)
-- Bu ayar sipariş geldiğinde admin panelinin anında güncellemesini sağlar.
begin;
  -- Eğer "supabase_realtime" yayını yoksa oluşturur (Genelde vardır)
  -- alter publication supabase_realtime add table public.products;
  -- alter publication supabase_realtime add table public.orders;
commit;

-- (Alternatif Yöntem: Supabase arayüzünden ilgili tabloya gidip "Enable Realtime" diyebilirsin)
alter publication supabase_realtime add table public.products;
alter publication supabase_realtime add table public.orders;

-- 4. Güvenlik İzinleri (Row Level Security)
-- Kimsenin veri okuma/yazma sorunu yaşamaması için "public" (herkese açık) izinleri veriyoruz.
-- PROD ortamına geçerken burayı kısıtlamak isteyebilirsin.

alter table public.products enable row level security;
alter table public.orders enable row level security;

-- Products tablosu için izinler
create policy "Herkese açık okuma (products)" on public.products for select using (true);
create policy "Herkese açık ekleme (products)" on public.products for insert with check (true);
create policy "Herkese açık güncelleme (products)" on public.products for update using (true);
create policy "Herkese açık silme (products)" on public.products for delete using (true);

-- Orders tablosu için izinler
create policy "Herkese açık okuma (orders)" on public.orders for select using (true);
create policy "Herkese açık ekleme (orders)" on public.orders for insert with check (true);
create policy "Herkese açık güncelleme (orders)" on public.orders for update using (true);
